# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: 'gd'

    twig:
        mode: 'lazy'

    cache: 'default'

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'

        aws_s3_resolver:
            aws_s3:
                client_config:
                    credentials:
                        key: "%amazon.s3.key%"
                        secret: "%amazon.s3.secret%"
                    region: "%amazon.s3.region%"
                    version: "%amazon.s3.version%"
                bucket: "%amazon.s3.bucket%"
                get_options:
                    Scheme: https

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%"

    filter_sets:
        min:
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail: { size: [ 150, 150 ], mode: inset, allow_upscale: true }
        min_premium:
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail: { size: [ 300, 300 ], mode: inset, allow_upscale: true }

when@prod:
    liip_imagine:
        cache: 'aws_s3_resolver'
