# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    amazon.s3.key: '%env(AWS_S3_KEY)%'
    amazon.s3.secret: '%env(AWS_S3_SECRET)%'
    amazon.s3.bucket: '%env(AWS_S3_BUCKET)%'
    amazon.s3.region: '%env(AWS_S3_REGION)%'
    amazon.s3.version: '2006-03-01'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $liipImagineServiceFilter: '@liip_imagine.service.filter'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
